### ISSUE TITLE
Один разработческий вопрос от дилетанта-сишарпника

### ISSUE THREAD

**Issue by mediaexplorer74** [JaneySprings/Cappuccino#1]
Никита, привет. 
Форкнул Вашу шарманку. Думал, это кросс-платформенный проект с применением Замарин Формс. Походу, я ошибся, и это некий инопланетный корабль, где Андроид-проект и АйОс проект сам по себе... 
Скажите, а MAUI-версии сего творения у Вас не нету? Или UNO-версии?
Или какого-нить файла-описания структуры/архитектуры Вашего решения.
Сам я пэхапешник, Си шарп лишь как хобби (оч. мало скиллов). 
Есть мечта лайтовый многоплатформенный клиент ВКшки собрать, включая таргет UWP (для Винды)

С уважением,
Андрей

**Comment by JaneySprings** [comment]
Привет. Начинал делать спайк, но времени не хватило. Вот сюда залил  https://github.com/JaneySprings/Cappuccino/tree/maui-spike/Cappuccino.App.Multiplatform, тут есть готовая авторизация и пример запроса `friends.get`. Он даже билдится.

Можешь `AppId` мой юзать, там есть разрешения на секцию `Messages`.

Надеюсь, ты сможешь из него что-то сделать😊
